name: Mirror Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: '1 3 * * 0'
  push:
    branches: [ "main" ]

env:
  PROJECT_NAME_REPO: "${GITHUB_REPOSITORY##*/}"
  DOCKER_IMAGES_TAG: "latest"
  DOCKER_IMAGES_FROM: "ollama/ollama:${{env.DOCKER_IMAGES_TAG}}"

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: self-hosted
    permissions:
      packages: write
      contents: read
    steps:
      - name: GetRepoName
        if: ( !cancelled() )
        run: |
           REF_NAME="${GITHUB_REPOSITORY##*/}"
           echo "PROJECT_NAME_REPO=${REF_NAME}" >> "$GITHUB_ENV" 
        shell: bash

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        if: ( !cancelled() )
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Log in to GitHub registry
      #   uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      #   if: ( !cancelled() )
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Log in to Tencent registry GZ
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        if: ( !cancelled() )
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.DOCKER_USERNAME_TENCENT }}
          password: ${{ secrets.DOCKER_PASSWORD_TENCENT }}

      - name: Log in to Tencent registry USW
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: uswccr.ccs.tencentyun.com
          username: ${{ secrets.DOCKER_USERNAME_TENCENT }}
          password: ${{ secrets.DOCKER_PASSWORD_TENCENT }}

      - name: PULL and push Docker images
        if: ( !cancelled() )
        run: |
           docker pull ${{ env.DOCKER_IMAGES_FROM }}
           docker tag ${{ env.DOCKER_IMAGES_FROM }} ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME_REPO }}:${{env.DOCKER_IMAGES_TAG}} ||true
           docker tag ${{ env.DOCKER_IMAGES_FROM }} ccr.ccs.tencentyun.com/${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME_REPO }}:${{env.DOCKER_IMAGES_TAG}} ||true
           docker tag ${{ env.DOCKER_IMAGES_FROM }} uswccr.ccs.tencentyun.com/${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME_REPO }}:${{env.DOCKER_IMAGES_TAG}} ||true
        shell: bash
